# Generated by Django 5.2.4 on 2025-07-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='review_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
